name: GitHub-Profile-3D-Cityscape

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d-city
    steps:
      - uses: actions/checkout@v3
      - uses: jasonlong/github-contribution-stats@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git diff --staged --quiet || git commit -m "Generated dramatic 3D cityscape"
          git push
